redis:
  image: dockerizedrupal/redis:1.1.0
  hostname: redis
  ports:
    - "6379:6379"
  volumes_from:
    - redis-data
  environment:
    - TIMEZONE=Etc/UTC
redis-data:
  image: dockerizedrupal/data:1.1.0
  hostname: redis-data
  volumes:
    - /redis
